src/Entity/Cart.php
<?php

namespace App\Entity;

use App\Repository\CartRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use phpDocumentor\Reflection\Types\Integer;
use App\Entity\Products;
use App\Entity\User;

/**
 * @ORM\Entity(repositoryClass=CartRepository::class)
 */
class Cart
{
     /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    public $id;
    /**
     * @ORM\ManyToOne(targetEntity=Products::class, inversedBy="productId", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    public $product_id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="userId", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    public $user_id;

    /**
     * @ORM\Column(type="integer")
     */

    public $quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getUserId(): ?User
    {
        return $this->user_id;
    }

    public function setUserId(?User $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getProductId(): ?Products
    {
        return $this->product_id;
    }

    public function setProductId(?Products $product_id): self
    {
        $this->product_id = $product_id;

        return $this;
    }
    public function __toString()
    {
        return $this->id;
    }
    public function getTotal(): float
    {
        return $this->getProductId()->getPrice() * $this->getQuantity();
    }
}

src/Form/CartType.php
<?php

namespace App\Form;

use App\Entity\Cart;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CartType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('id')
            ->add('product_id')
            ->add('user_id')
            ->add('quantity')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cart::class,
        ]);
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Cart;
use App\Form\CartType;
use App\Entity\Products;
use App\Entity\User;
use App\Form\ProductsType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\Extension\HttpFoundation\HttpFoundationRequestHandler;
use Symfony\Component\HttpFoundation\Request;
use function PHPUnit\Framework\stringContains;

class CartController extends AbstractController
{
    #[Route('/cart', name: 'cart')]
    public function index(): Response
    {
        return $this->render('cart/index.html.twig', [
            'cart' => 'CartController',
        ]);
    }
    #[Route('/cart/all/ascending', name: 'cart_ascending')]
    public function listAscendingCart(): Response
    {   
        // Call Entity Manager
            $em = $this
            ->getDoctrine()
            ->getManager();

        // Call UserRepo
        $cartRepo = $em->getRepository(Cart::class);

        // Call function
        $result = $cartRepo->getCartAscending();

        // Return result to View
        return $this->render('cart/list.html.twig', [
            'cart' => $result
        ]);
    }
    #[Route('/cart/create', name: 'cart_create', methods: ['GET', 'POST'])]
    public function createAction(Request $request, EntityManagerInterface $entityManager): Response
    {
        $cart = new Cart();
        $form = $this->createForm(CartType::class, $cart);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid())
        {
            $entityManager->persist($cart);
            $entityManager->flush();
            return $this->redirectToRoute('cart_ascending',[], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('cart/create.html.twig',[
            'cart'=>$cart,
            'form'=>$form]);
    }
    #[Route('/cart/detail/{id}', name: 'cart_detail')]
    public function detailAction($id)
    {
        $cart = $this->getDoctrine()
            ->getRepository('App:Cart')
            ->find($id);
        return $this->render('cart/detail.html.twig', [
            'cart' => $cart
        ]);
    }
    #[Route('/cart/delete/{id}', name: 'cart_delete')]
    public function deleteAction($id)
    {
        $em = $this
            ->getDoctrine()
            ->getManager();
        $cart = $em
              ->getRepository('App:Cart')
              ->find($id);
        $em->remove($cart);
        $em->flush();

        $this->addFlash(
            'error',
            'Cart deleted'
        );

        return $this->redirectToRoute('cart_ascending');
    }
    #[Route('/cart/edit/{id}', name: 'cart_edit')]
    public function editAction($id, Request $request)
    {
        $em = $this
            ->getDoctrine()
            ->getManager();
        $cart = $em
              ->getRepository('App:Cart')
              ->find($id);

        $form = $this->createForm(CartType::class, $cart);

        if ($this->saveEditedData($form, $request, $cart)) {
            $this->addFlash(
                'notice',
                'Cart Edited'
            );
            return $this->redirectToRoute('cart_ascending');
        }

        return $this->render('cart/edit.html.twig', [
            'form' => $form->createView()
        ]);
    }
    public function saveEditedData($form, $request, $cart)
    {
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cart->setQuantity($request->request->get('cart')['quantity']);

            $em = $this
                ->getDoctrine()
                ->getManager();
            $em->persist($cart);
            $em->flush();

            return true;
        }

        return false;
    }
}

templates/cart/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ form_start(form) }}
    <div class="form-group">
        <label for="id">ID:</label>
        {{ form_widget(form.id,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Id'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.id) }}
        </div>
    </div>
    <div class="form-group">
        <label for="name">Product Id:</label>
        {{ form_widget(form.product_id,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Product Id'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.product_id) }}
        </div>
    </div>
     <div class="form-group">
        <label for="id">User Id:</label>
        {{ form_widget(form.user_id,{
            'attr':{
                'class':'form-control',
                'placeholder': 'User Id'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.user_id) }}
        </div>
    </div>
         <div class="form-group">
        <label for="id">Quantity:</label>
        {{ form_widget(form.quantity,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Quantity'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.quantity) }}
        </div>
    <div>
    
    <input type="submit" name="create_cart" value="Create" class="btn btn-primary"/>
    <a href="{{ path('cart_ascending') }}" class="btn btn-danger">Cancel</a>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/cart/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('cart_ascending') }}" class=" btn btn-primary">Back to Cart List</a>
    <br>

    <table class="table table-striped">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">{{ cart.id }}</th>
        </tr>
        <tr>
            <th scope="col">Product ID</th>
            <th scope="col">{{ cart.product_id }}</th>
        </tr>
        <tr>
            <th scope="col">User Id</th>
            <th scope="col">{{ cart.user_id }}</th>
        </tr>
        <tr>
            <th scope="col">Quantity</th>
            <th scope="col">{{ cart.quantity }}</th>
        </tr>
        <tr>
            <th scope="col">Price</th>
            <th scope="col">{{cart.total}}</th>
        </tr>
    </table>
{% endblock %}

templates/cart/edit.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ form_start(form) }}
    <div class="form-group">
        <label for="id">ID:</label>
        {{ form_widget(form.id,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Id'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.id) }}
        </div>
    </div>
    <div class="form-group">
        <label for="name">Product Id:</label>
        {{ form_widget(form.product_id,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Product Id'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.product_id) }}
        </div>
    </div>
     <div class="form-group">
        <label for="id">User Id:</label>
        {{ form_widget(form.user_id,{
            'attr':{
                'class':'form-control',
                'placeholder': 'User Id'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.user_id) }}
        </div>
    </div>
         <div class="form-group">
        <label for="id">Quantity:</label>
        {{ form_widget(form.quantity,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Quantity'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.quantity) }}
        </div>
    <div>
    
    <input type="submit" name="edit_cart" value="Edit" class="btn btn-primary"/>
    <a href="{{ path('cart_ascending') }}" class="btn btn-danger">Cancel</a>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CartController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ cart }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/mama1/gcd0904-project-web/src/Controller/CartController.php'|file_link(0) }}">src/Controller/CartController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/mama1/gcd0904-project-web/templates/cart/index.html.twig'|file_link(0) }}">templates/cart/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/cart/list.html.twig
{% extends 'base.html.twig' %}

{% block body %}
        <div class="bs-example" data-example-id="striped-table">
        <div class="d-flex justify-content-end">
            <a href="{{ path('cart_create') }}" class=" btn btn-primary">Add Product to Cart</a>
        </div>
        <br>

        <table class="table table-bordered">
            <thead class="thead-dark">
            <tr>
                <th scope="col">ID</th>
                <th scope="col">PRODUCT ID</th>
                <th scope="col">USER ID</th>
                <th scope="col">QUANTITY</th>
            </tr>
            </thead>
            <tbody>
            {% for car in cart %}
                <tr>
                    <th scope="row">{{ car.id }}</th>
                    <td>{{ car.product_id }}</td>
                    <td>{{ car.user_id}}</td>
                    <td>{{ car.quantity}}</td>
                    <td>
                        <a href="{{ path('cart_detail', {'id': car.id}) }} " class='btn btn-success'> View </a>
                        <a href="{{ path('cart_edit', {'id': car.id}) }}" class='btn btn-primary'>Edit</a>
                        <a href="{{ path('cart_delete', {'id': car.id}) }}" class='btn btn-danger'>Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
{% endblock %}